services: 
    web-server:
      image: nginx:latest
      container_name: webdev-nginx
      ports:
        - "80:80"
        - "443:443"
      networks:
        - web-dev
      volumes:
        - ./config/server/:/etc/nginx/conf.d/
        - .:/var/www/projects
        - ./config/server/ssl/:/var/www/ssl

    php:
      build:
        dockerfile: ./php.dockerfile
        context: .
      image: php:8.4-fpm
      container_name: webdev-php
      volumes: 
        - ./:/var/www/projects
      ports: 
        - "9000:9000"
      networks: 
        - web-dev

    db:
      image: percona/percona-server:latest
      container_name: webdev-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - 3306:3306
      networks: 
        - web-dev

networks: 
      web-dev:
        driver: bridge